### ISSUE TITLE
Feature: Ability to download files to sessionID folder

### ISSUE THREAD

**Issue by arturmkr** [selenide/selenide-selenoid#1]
Problem:
Configuration.downloadsFolder variable is static.
So, all download files from all tests would be placed to the same location. (For example, target/downloads)
If it's needed to differentiate download files by each test - it won't be possible to do.
Also, multiple tests, which run in parallel and download the same file, would cause a problem.

Proposed solution:
Add boolean configuration parameter - Configuration.createSessionIdFolderForDownloads
If this parameter is set to true, files that are downloaded in the scope of the session - would be places in the sessionId folder.
For example:
target/downloads/chrome-86-0-0aaad100-bdb6-480a-9022-090d46b5fe2

**Comment by asolntsev** [comment]
@arturmkr At a first glance, it seems that there is no problems. 
Method `$.download()` creates a _unique subfolder_ in `Configuration.downloadsFolder` _for every downloaded file_. So tests do not conflict with each other.
