### ISSUE TITLE
Need to implement event firing when Selenoid starts video recording

### ISSUE THREAD

**Issue by toolateitsme** [selenide/selenide-selenoid#18]
Can you implement this feature? 

For some projects i need to know, when this process has started

Since WebDriverListener does not provide this functionality, akin to WebDriverRunner, or Selenide facade, is it good idea to implement somehow this idea here?

Also, could you tell me some workaround, how to catch video-recording event, if is possible?

**Comment by BorisOsipov** [comment]
@toolateitsme can you point where `video-recording event` mentioned in [selenoid docs](https://aerokube.com/selenoid/latest/)?

**Comment by toolateitsme** [comment]
I can not. Also, there is no event fire even in selenoid logs. 

<img width="1471" alt="image" src="https://user-images.githubusercontent.com/6512625/178664084-eb548069-b526-4429-9f0f-cad355be8c47.png">

Should i nofify and ask selenoid team for implementation of this event firing?

**Comment by BorisOsipov** [comment]
>Should i nofify and ask selenoid team for implementation of this event firing?

I cant answer because IDK why do you need such event and what does a real problem you try yo solve.

**Comment by asolntsev** [comment]
@toolateitsme I guess there no such event. When  you create a webdriver, selenoid starts a container with video recording. When you close the webdriver, selenoid stops the container, and the video recording ends.
