### ISSUE TITLE
Make the method `$.download()` wait for the full completion of download

### ISSUE THREAD

**Issue by bereg2k** [selenide/selenide-selenoid#19]
Implement the same feature for waiting for files to be fully downloaded as in [#1804](https://github.com/selenide/selenide/pull/1804).

UPD For example, here is a complain about the same problem (and steps to reproduce): https://automated-testing.info/t/ne-skachivaetsya-fajl-cherez-download-v-selenide-selenoid/28327

**Comment by asolntsev** [comment]
good point, need to implement it.

**Comment by asolntsev** [comment]
Implemented in https://github.com/selenide/selenide-selenoid/pull/27/
