### ISSUE TITLE
got Failed-Download error and wrong filename

### ISSUE THREAD

**Issue by cocobear** [selenide/selenide-selenoid#5]
when I using local browser, I got error:

> Failed-Download error.

![](https://i.stack.imgur.com/thNbL.png)

I noticed it create a folder named "1612870041162_58804_1" when case run,
but when testcase finished, the folder had gone.  
new folder named "140d665a-3273-4ce6-a1f5-f4096061d13c" created, and
file download in this folder with wrong name ：“Task Management_20210209192751.csv.crdownload”

Here is snipecode:
```
	    Configuration.fileDownload = FileDownloadMode.FOLDER;
	    Configuration.reportsFolder = "target/surefire-reports";
	    Configuration.downloadsFolder = "target/downloads";
.....

File f = $(By.xpath(xpath)).download();
	    
````
I can get  file content with object `f` which is corrent, but filename is wrong

How can I do ?

**Comment by asolntsev** [comment]
@cocobear As long as I understand, filename "*.crdownload" means that the file _is being downloaded_ at the moment. Once the downloading is completed, this file should disappear, and the final file should appear in the downloads folder. 

* Probably you just need to set bigger timeout? It seems your downloading is just too slow. 
* You can call `$.download()` method with `Filter` parameter:
```
import static com.codeborne.selenide.files.FileFilters.withExtension;

File f = $(By.xpath(xpath)).download(withExtension(".csv"));
```
